package com.waylanpunch.mymagazine.dao;

import com.waylanpunch.mymagazine.pojo.Attachment;
import com.waylanpunch.mymagazine.pojo.AttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachments
     *
     * @mbg.generated
     */
    long countByExample(AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachments
     *
     * @mbg.generated
     */
    int deleteByExample(AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachments
     *
     * @mbg.generated
     */
    int insert(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachments
     *
     * @mbg.generated
     */
    int insertSelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachments
     *
     * @mbg.generated
     */
    List<Attachment> selectByExample(AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachments
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Attachment record, @Param("example") AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachments
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Attachment record, @Param("example") AttachmentExample example);
}