package com.waylanpunch.mymagazine.dao;

import com.waylanpunch.mymagazine.pojo.Meta;
import com.waylanpunch.mymagazine.pojo.MetaExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface MetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated
     */
    long countByExample(MetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated
     */
    int deleteByExample(MetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated
     */
    int insert(Meta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated
     */
    int insertSelective(Meta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated
     */
    List<Meta> selectByExample(MetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Meta record, @Param("example") MetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Meta record, @Param("example") MetaExample example);
}