package com.waylanpunch.mymagazine.dao;

import com.waylanpunch.mymagazine.pojo.Option;
import com.waylanpunch.mymagazine.pojo.OptionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_options
     *
     * @mbg.generated
     */
    long countByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_options
     *
     * @mbg.generated
     */
    int deleteByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_options
     *
     * @mbg.generated
     */
    int insert(Option record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_options
     *
     * @mbg.generated
     */
    int insertSelective(Option record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_options
     *
     * @mbg.generated
     */
    List<Option> selectByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_options
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Option record, @Param("example") OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_options
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Option record, @Param("example") OptionExample example);
}