package com.waylanpunch.mymagazine.dao;

import com.waylanpunch.mymagazine.pojo.Relationship;
import com.waylanpunch.mymagazine.pojo.RelationshipExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface RelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated
     */
    long countByExample(RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated
     */
    int deleteByExample(RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated
     */
    int insert(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated
     */
    int insertSelective(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated
     */
    List<Relationship> selectByExample(RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Relationship record, @Param("example") RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Relationship record, @Param("example") RelationshipExample example);
}