package com.waylanpunch.mymagazine.pojo;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.article_id
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.slug
     *
     * @mbg.generated
     */
    private String slug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.modified
     *
     * @mbg.generated
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.tags
     *
     * @mbg.generated
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.categories
     *
     * @mbg.generated
     */
    private String categories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.hits
     *
     * @mbg.generated
     */
    private Integer hits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.comments_number
     *
     * @mbg.generated
     */
    private Integer commentsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.allow_comment
     *
     * @mbg.generated
     */
    private Boolean allowComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.allow_ping
     *
     * @mbg.generated
     */
    private Boolean allowPing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.allow_feed
     *
     * @mbg.generated
     */
    private Boolean allowFeed;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated
     */
    public Article(Integer articleId, String title, String slug, Date created, Date modified, String content, Integer userId, String type, String status, String tags, String categories, Integer hits, Integer commentsNumber, Boolean allowComment, Boolean allowPing, Boolean allowFeed) {
        this.articleId = articleId;
        this.title = title;
        this.slug = slug;
        this.created = created;
        this.modified = modified;
        this.content = content;
        this.userId = userId;
        this.type = type;
        this.status = status;
        this.tags = tags;
        this.categories = categories;
        this.hits = hits;
        this.commentsNumber = commentsNumber;
        this.allowComment = allowComment;
        this.allowPing = allowPing;
        this.allowFeed = allowFeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated
     */
    public Article() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.article_id
     *
     * @return the value of t_articles.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.article_id
     *
     * @param articleId the value for t_articles.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.title
     *
     * @return the value of t_articles.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.title
     *
     * @param title the value for t_articles.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.slug
     *
     * @return the value of t_articles.slug
     *
     * @mbg.generated
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.slug
     *
     * @param slug the value for t_articles.slug
     *
     * @mbg.generated
     */
    public void setSlug(String slug) {
        this.slug = slug == null ? null : slug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.created
     *
     * @return the value of t_articles.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.created
     *
     * @param created the value for t_articles.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.modified
     *
     * @return the value of t_articles.modified
     *
     * @mbg.generated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.modified
     *
     * @param modified the value for t_articles.modified
     *
     * @mbg.generated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.content
     *
     * @return the value of t_articles.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.content
     *
     * @param content the value for t_articles.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.user_id
     *
     * @return the value of t_articles.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.user_id
     *
     * @param userId the value for t_articles.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.type
     *
     * @return the value of t_articles.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.type
     *
     * @param type the value for t_articles.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.status
     *
     * @return the value of t_articles.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.status
     *
     * @param status the value for t_articles.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.tags
     *
     * @return the value of t_articles.tags
     *
     * @mbg.generated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.tags
     *
     * @param tags the value for t_articles.tags
     *
     * @mbg.generated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.categories
     *
     * @return the value of t_articles.categories
     *
     * @mbg.generated
     */
    public String getCategories() {
        return categories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.categories
     *
     * @param categories the value for t_articles.categories
     *
     * @mbg.generated
     */
    public void setCategories(String categories) {
        this.categories = categories == null ? null : categories.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.hits
     *
     * @return the value of t_articles.hits
     *
     * @mbg.generated
     */
    public Integer getHits() {
        return hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.hits
     *
     * @param hits the value for t_articles.hits
     *
     * @mbg.generated
     */
    public void setHits(Integer hits) {
        this.hits = hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.comments_number
     *
     * @return the value of t_articles.comments_number
     *
     * @mbg.generated
     */
    public Integer getCommentsNumber() {
        return commentsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.comments_number
     *
     * @param commentsNumber the value for t_articles.comments_number
     *
     * @mbg.generated
     */
    public void setCommentsNumber(Integer commentsNumber) {
        this.commentsNumber = commentsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.allow_comment
     *
     * @return the value of t_articles.allow_comment
     *
     * @mbg.generated
     */
    public Boolean getAllowComment() {
        return allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.allow_comment
     *
     * @param allowComment the value for t_articles.allow_comment
     *
     * @mbg.generated
     */
    public void setAllowComment(Boolean allowComment) {
        this.allowComment = allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.allow_ping
     *
     * @return the value of t_articles.allow_ping
     *
     * @mbg.generated
     */
    public Boolean getAllowPing() {
        return allowPing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.allow_ping
     *
     * @param allowPing the value for t_articles.allow_ping
     *
     * @mbg.generated
     */
    public void setAllowPing(Boolean allowPing) {
        this.allowPing = allowPing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.allow_feed
     *
     * @return the value of t_articles.allow_feed
     *
     * @mbg.generated
     */
    public Boolean getAllowFeed() {
        return allowFeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.allow_feed
     *
     * @param allowFeed the value for t_articles.allow_feed
     *
     * @mbg.generated
     */
    public void setAllowFeed(Boolean allowFeed) {
        this.allowFeed = allowFeed;
    }
}