package com.waylanpunch.mymagazine.pojo;

import java.util.Date;

public class Attachment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attachments.attachment_id
     *
     * @mbg.generated
     */
    private Integer attachmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attachments.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attachments.file_type
     *
     * @mbg.generated
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attachments.file_key
     *
     * @mbg.generated
     */
    private String fileKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attachments.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attachments.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachments
     *
     * @mbg.generated
     */
    public Attachment(Integer attachmentId, String fileName, String fileType, String fileKey, Integer userId, Date created) {
        this.attachmentId = attachmentId;
        this.fileName = fileName;
        this.fileType = fileType;
        this.fileKey = fileKey;
        this.userId = userId;
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachments
     *
     * @mbg.generated
     */
    public Attachment() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attachments.attachment_id
     *
     * @return the value of t_attachments.attachment_id
     *
     * @mbg.generated
     */
    public Integer getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attachments.attachment_id
     *
     * @param attachmentId the value for t_attachments.attachment_id
     *
     * @mbg.generated
     */
    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attachments.file_name
     *
     * @return the value of t_attachments.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attachments.file_name
     *
     * @param fileName the value for t_attachments.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attachments.file_type
     *
     * @return the value of t_attachments.file_type
     *
     * @mbg.generated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attachments.file_type
     *
     * @param fileType the value for t_attachments.file_type
     *
     * @mbg.generated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attachments.file_key
     *
     * @return the value of t_attachments.file_key
     *
     * @mbg.generated
     */
    public String getFileKey() {
        return fileKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attachments.file_key
     *
     * @param fileKey the value for t_attachments.file_key
     *
     * @mbg.generated
     */
    public void setFileKey(String fileKey) {
        this.fileKey = fileKey == null ? null : fileKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attachments.user_id
     *
     * @return the value of t_attachments.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attachments.user_id
     *
     * @param userId the value for t_attachments.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attachments.created
     *
     * @return the value of t_attachments.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attachments.created
     *
     * @param created the value for t_attachments.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}