package com.waylanpunch.mymagazine.pojo;

import java.util.Date;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.log_id
     *
     * @mbg.generated
     */
    private Integer logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.data
     *
     * @mbg.generated
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated
     */
    public Log(Integer logId, String action, String data, Integer userId, String ip, Date created) {
        this.logId = logId;
        this.action = action;
        this.data = data;
        this.userId = userId;
        this.ip = ip;
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated
     */
    public Log() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.log_id
     *
     * @return the value of t_logs.log_id
     *
     * @mbg.generated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.log_id
     *
     * @param logId the value for t_logs.log_id
     *
     * @mbg.generated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.action
     *
     * @return the value of t_logs.action
     *
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.action
     *
     * @param action the value for t_logs.action
     *
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.data
     *
     * @return the value of t_logs.data
     *
     * @mbg.generated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.data
     *
     * @param data the value for t_logs.data
     *
     * @mbg.generated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.user_id
     *
     * @return the value of t_logs.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.user_id
     *
     * @param userId the value for t_logs.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.ip
     *
     * @return the value of t_logs.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.ip
     *
     * @param ip the value for t_logs.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.created
     *
     * @return the value of t_logs.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.created
     *
     * @param created the value for t_logs.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}